# Generated by Django 5.2.11 on 2026-03-09 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_tickets", "0004_alter_comment_ticket_ticketattachment_ticketcomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticketattachment",
            old_name="created_at",
            new_name="uploaded_at",
        ),
        migrations.AlterField(
            model_name="ticketattachment",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="app_tickets.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="ticketcomment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
