# Generated by Django 5.2.11 on 2026-03-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_tickets", "0005_rename_created_at_ticketattachment_uploaded_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticketattachment",
            old_name="uploaded_at",
            new_name="created_at",
        ),
    ]
