# Generated by Django 5.2.11 on 2026-02-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0002_userchecklisttask"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressBookContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
