# Generated by Django 5.2.11 on 2026-02-18 12:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_kb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text="Supports Rich Text / HTML"
            ),
        ),
    ]
