# Generated by Django 5.2.11 on 2026-02-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_kb", "0002_alter_article_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="kb_attachments/"),
        ),
    ]
