# Generated by Django 5.2.11 on 2026-02-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_assets",
            "0002_location_asset_assigned_to_asset_make_asset_model_no_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="specifications",
        ),
    ]
