# Generated by Django 5.2.11 on 2026-02-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_assets", "0003_remove_asset_specifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="assigned_to",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
