# Generated by Django 5.2.11 on 2026-02-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_assets", "0004_alter_asset_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
