# Generated by Django 5.2.11 on 2026-02-19 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_assets", "0005_asset_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="alert_email",
            field=models.EmailField(
                blank=True,
                help_text="Email to notify if device goes offline",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="is_monitored",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("latency_ms", models.FloatField(blank=True, null=True)),
                ("packet_loss", models.FloatField(default=0.0)),
                ("is_online", models.BooleanField(default=False)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ping_records",
                        to="app_assets.asset",
                    ),
                ),
            ],
        ),
    ]
