# Generated by Django 5.2.11 on 2026-02-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_assets", "0006_asset_alert_email_asset_is_monitored_pingrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="specifications",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
