# Generated by Django 5.2.11 on 2026-02-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_forms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formanswer",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
